fix: adjust to allow close on click outside
FuelLabs/fuel-ui pull request #190
Opened 2023-01-27 03:11 UTC by LuizAsFight

This PR 
- replace `overlay` with `underlay` to populate underlay container
- creates `overlay` style to use in overlay container
- add pointerEvent behaviors to fix bug not allowing to close on click outside

2023-01-27 07:38 UTC, luizstacio requested changes
When closing, the animation is not working, the current version animates out of the screen also.

2023-01-27 21:46 UTC, LuizAsFight commented
fixed @luizstacio could you check again ? ty

2023-01-28 20:12 UTC, luizstacio requested changes
Looks at the radix docs, I test locally here, and to achieve the result, we just need to pass, `isDismissable: true` on `useOverlay`.

I have tested inside the Wallet: `<Drawer type="menu" size={220} containerRef={ref} isDismissable={true}>` It works.

2023-01-30 21:15 UTC, luizstacio approved these changes

2023-01-30 21:15 UTC, merged