feat: add asset dropdown to amount input
FuelLabs/fuel-ui pull request #223
Opened 2023-03-23 22:46 UTC by matt-user

closes #222

2023-04-07 00:50 UTC, luizstacio requested changes

2023-04-07 00:50 UTC, luizstacio commented on design-system/react/src/components/InputAmount/InputAmount.tsx
> +                </Flex>
On the fuel-ui side, this should be just a button that enables the upper application to implement the selector in a better way like a popup.

2023-04-07 00:51 UTC, luizstacio commented on design-system/react/src/components/InputAmount/InputAmount.stories.tsx
> +  assetInfo: [
With my comment about the button this asset list should not exists instead we can only add a `asset` prop that informs what is selected.

2023-04-10 18:15 UTC, luizstacio requested changes

2023-04-12 01:55 UTC, luizstacio requested changes
1. The component's layout needs more space around the button. We can also increase the height of the button.
2. We can follow the new design image attached.
3. When the asset is not passed, the layout should be different without the button but with the layout in the correct order.
4. As we don't have asset list inside the component anymore the images can be deleted
<img width="347" alt="Screenshot 2023-04-11 at 22 51 37" src="https://user-images.githubusercontent.com/3941923/231326795-e020744b-b9ee-4671-9b8c-353a4d777ddc.png">
<img width="783" alt="Screenshot 2023-04-11 at 22 53 00" src="https://user-images.githubusercontent.com/3941923/231327248-54d2d8cd-d491-4f06-9572-3e654338feba.png">
<img width="788" alt="Screenshot 2023-04-11 at 22 54 28" src="https://user-images.githubusercontent.com/3941923/231327250-b78923a6-9d95-4230-87d8-4ce14e914764.png">

2023-04-18 20:43 UTC, luizstacio requested changes
With the new changes on the design the component looks off from the design.

2023-04-24 20:52 UTC, luizstacio commented
I think we can hold the fixes here to after the PR #232 is merged

2023-05-02 18:52 UTC, LuizAsFight requested changes
looks good, few changes other than the comments, related to Loader component:


- height is different
- elements position doesn't match
  - let's make loader elements match the "With Asset" version

https://user-images.githubusercontent.com/8636507/235756493-ea6f1782-4a18-4614-88dc-3f4dd765b429.mov

2023-05-02 18:52 UTC, LuizAsFight commented on design-system/react/src/components/InputAmount/InputAmount.tsx
> +  onClickAsset?: (val: PressEvent) => void;
```suggestion
  onClickAsset?: (e: PressEvent) => void;
```

2023-05-02 18:52 UTC, LuizAsFight commented on design-system/react/src/components/InputAmount/InputAmount.tsx
> +  asset?: Asset;
can we add other optional prop `assetTooltip?: string`?

then if user informs `assetTooltip` we put the tooltip in the asset button

2023-05-02 18:52 UTC, LuizAsFight commented on design-system/react/src/components/InputAmount/InputAmount.tsx
> +              )}
to increase this component flexibility, let's include other use case: when has asset, but doesn't support multiple assets

1- if there's `asset` and no `onClickAsset`, should show the button still, but in readOnly mode . also should hide "caretDown" icon
2- if there's `asset` and `onClickAsset`, show in the way it is now: button active to click + "caretDown" icon

2023-05-02 18:52 UTC, LuizAsFight commented on design-system/react/src/components/InputAmount/InputAmount.tsx
> +    width: '352px',
let's not force `width` , component will resize to parent

2023-05-02 18:52 UTC, LuizAsFight commented on design-system/react/src/components/InputAmount/InputAmount.tsx
> +    height: '80px',
can we use sizing variables here? I was testing and `$20` will match 80px size

2023-05-02 18:52 UTC, LuizAsFight commented on design-system/react/src/components/InputAmount/InputAmount.tsx
> +    height: '24px',
```suggestion
    height: '$6',
```

2023-05-02 18:52 UTC, LuizAsFight commented on design-system/react/src/components/InputAmount/InputAmount.tsx
> +    height: '80px',
```suggestion
    height: '$20',
```

2023-05-02 18:52 UTC, LuizAsFight commented on design-system/react/src/components/InputAmount/InputAmount.tsx
> +    borderRadius: '3px',
sizing variables

2023-05-02 18:52 UTC, LuizAsFight commented on design-system/react/src/components/InputAmount/InputAmount.tsx
> +    width: '72px',
sizing variables

2023-05-02 18:52 UTC, LuizAsFight commented on design-system/react/package.json
> +    "@fuel-wallet/types": "^0.7.2",
is wallet sdk needed in fuel-ui?

2023-05-02 18:52 UTC, LuizAsFight commented on design-system/react/tsconfig.json
> +    "types": ["@fuel-wallet/sdk", "chrome", "jest"]
is wallet sdk needed in fuel-ui?

2023-05-02 19:13 UTC, pedronauck requested changes

2023-05-02 19:13 UTC, pedronauck commented on design-system/react/src/components/InputAmount/InputAmount.tsx
> +      <Text color="intentsBase9" css={styles.heading}>
Try to avoid mixing things like here, instead of defining `color` here, put this definition inside `style.heading`

2023-05-02 19:13 UTC, pedronauck commented on design-system/react/src/components/InputAmount/InputAmount.tsx
> +      <Flex align="center" css={styles.secondRow}>
Try to avoid mixing things like here, instead of defining `align` here, put this definition inside `styles.secondRow`

2023-05-02 19:13 UTC, pedronauck commented on design-system/react/src/components/InputAmount/InputAmount.tsx
> +                  <Text fontSize="xs" color="intentsBase12">
Always avoid props to define css, instead use always the `style.*` to create definitions

2023-05-03 18:44 UTC, LuizAsFight requested changes

2023-05-03 21:48 UTC, LuizAsFight requested changes
the "not clickable" version of asset button:
- should not be clickable / or not have any reaction when clicking (rn there is a tiny reaction)
- should not look disabled

https://user-images.githubusercontent.com/8636507/236057120-bf67899f-02f0-4fc0-8a15-a98f0a870710.mov

2023-05-03 21:48 UTC, LuizAsFight commented on design-system/react/src/components/InputAmount/InputAmount.tsx
> +                    {tokenImage(asset.name, asset.imageUrl)}
can we use directly the component here ?

2023-05-03 21:48 UTC, LuizAsFight commented on design-system/react/src/components/InputAmount/InputAmount.tsx
> +                    disabled={!onClickAsset}
I guess we should use readOnly? I will explain why in other comment with video

2023-05-04 23:02 UTC, LuizAsFight submitted a review, later dismissed
great work @matt-user

2023-05-07 23:43 UTC, luizstacio approved these changes

2023-05-08 16:29 UTC, pedronauck approved these changes

2023-05-08 16:46 UTC, merged