feat: add Nav component
FuelLabs/fuel-ui pull request #316
Opened 2023-08-31 20:53 UTC by pedronauck

⭐ Closes FRO-460

2023-09-01 15:15 UTC, luizstacio reviewed
@pedronauck  I think we should add to the storybook the mobile view of the nav

2023-09-05 23:00 UTC, luizstacio requested changes
- The animation when opening the menu mobile looks a bit weird as the content loads first them the container.
- When we click on the link it shows a weird outline 
<img width="1115" alt="Screenshot 2023-09-05 at 7 58 02 PM" src="https://github.com/FuelLabs/fuel-ui/assets/3941923/67505f03-67a4-4338-91be-f1e5ece19a1e">

2023-09-05 23:11 UTC, pedronauck commented
@luizstacio the animation was adjusted, can you check now?

2023-09-06 16:38 UTC, luizstacio approved these changes

2023-09-06 16:38 UTC, merged